# Generated by Django 4.2.27 on 2026-01-03 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, verbose_name='계좌번호')),
                ('account_password', models.CharField(max_length=255, verbose_name='계좌비밀번호')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API 키')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API 시크릿')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 자산 (예수금+보유종목현재가치)')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='예수금')),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유종목현재가치')),
                ('profit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='수익률 (%)')),
                ('investment_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='투자상한선')),
                ('buy_enabled', models.BooleanField(default=True, verbose_name='매수동작여부')),
                ('sell_enabled', models.BooleanField(default=True, verbose_name='매도동작여부')),
                ('unified_margin', models.BooleanField(blank=True, default=False, null=True, verbose_name='통합증거금 여부')),
                ('overseas_etp_enabled', models.BooleanField(blank=True, default=False, null=True, verbose_name='해외 ETP 거래 가능 여부')),
                ('derivative_etf_enabled', models.BooleanField(blank=True, default=False, null=True, verbose_name='파생 ETF 거래 가능 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='브로커명')),
                ('country', models.CharField(choices=[('KR', '한국'), ('US', '미국'), ('UK', '영국'), ('JP', '일본'), ('CN', '중국')], max_length=2, verbose_name='국가')),
                ('is_crypto_exchange', models.BooleanField(default=False, verbose_name='암호화폐거래소 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '브로커',
                'verbose_name_plural': '브로커들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True, verbose_name='티커')),
                ('name', models.CharField(max_length=200, verbose_name='종목명')),
                ('currency', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], max_length=10, verbose_name='화폐단위')),
                ('is_crypto', models.BooleanField(default=False, verbose_name='암호화폐 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='trading.broker', verbose_name='브로커')),
            ],
            options={
                'verbose_name': '종목',
                'verbose_name_plural': '종목들',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=10, verbose_name='매수/매도')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], max_length=10, verbose_name='주문타입')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='지정가 (지정가 주문인 경우 필수)')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('PARTIALLY_FILLED', '부분체결'), ('FILLED', '체결완료'), ('CANCELLED', '취소됨'), ('REJECTED', '거부됨')], default='PENDING', max_length=20, verbose_name='주문상태')),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='체결수량')),
                ('average_filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='평균체결가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='체결일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.account', verbose_name='계좌')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trading.broker', verbose_name='브로커'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'broker', 'account_number')},
        ),
    ]
