# Generated by Django 4.2.27 on 2026-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='외부 주문 ID (브로커에서 반환한 주문 ID)'),
        ),
    ]
