# Generated by Django 4.2.27 on 2026-01-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_external_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='is_delisted',
            field=models.BooleanField(default=False, verbose_name='상장폐지 여부'),
        ),
    ]
