# Generated by Django 4.2.27 on 2026-01-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_symbol_is_delisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRealizedProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='실현 손익')),
                ('realized_profit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='실현 손익률 (%)')),
                ('total_buy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='총 매수 금액')),
                ('total_sell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='총 매도 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_profits', to='trading.account', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '일일 실현 손익',
                'verbose_name_plural': '일일 실현 손익들',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'date'], name='trading_dai_account_b36789_idx'), models.Index(fields=['date'], name='trading_dai_date_01ef38_idx')],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
