# Generated by Django 4.2.27 on 2026-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_broker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='액세스 토큰'),
        ),
        migrations.AddField(
            model_name='account',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='리프레시 토큰'),
        ),
        migrations.AddField(
            model_name='account',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료 시간'),
        ),
        migrations.AddField(
            model_name='account',
            name='token_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='토큰 발급 시간'),
        ),
    ]
