# Generated by Django 4.2.27 on 2026-01-04 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_account_access_token_account_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유 수량')),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='평균 매수가')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='현재가')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 가치 (수량 * 현재가)')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='평가 손익')),
                ('profit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='수익률 (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.account', verbose_name='계좌')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '보유 종목',
                'verbose_name_plural': '보유 종목들',
                'ordering': ['-total_value'],
                'indexes': [models.Index(fields=['account', 'symbol'], name='trading_hol_account_4ae6f1_idx'), models.Index(fields=['account'], name='trading_hol_account_5522b6_idx')],
                'unique_together': {('account', 'symbol')},
            },
        ),
    ]
