# Generated by Django 4.2.27 on 2026-01-04 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_balance_krw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='예수금 (KRW)'),
        ),
        migrations.AddField(
            model_name='account',
            name='cash_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='예수금 (USD)'),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_value_krw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유종목현재가치 (KRW)'),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_value_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유종목현재가치 (USD)'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_assets_krw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 자산 (KRW)'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_assets_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 자산 (USD)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='예수금 - 원화 기준'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유종목현재가치 - 원화 기준'),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 자산 (예수금+보유종목현재가치) - 원화 기준'),
        ),
    ]
