# Generated by Django 4.2.27 on 2026-01-04 08:09

from django.db import migrations
from decimal import Decimal


def migrate_legacy_fields_to_currency_fields(apps, schema_editor):
    """기존 필드 데이터를 통화별 필드로 복사"""
    Account = apps.get_model('trading', 'Account')
    
    for account in Account.objects.all():
        # 기존 필드가 있고 통화별 필드가 0인 경우에만 복사
        if account.cash_balance and account.cash_balance_krw == 0:
            account.cash_balance_krw = account.cash_balance
        if account.stock_value and account.stock_value_krw == 0:
            account.stock_value_krw = account.stock_value
        if account.total_assets and account.total_assets_krw == 0:
            account.total_assets_krw = account.total_assets
        
        account.save(update_fields=[
            'cash_balance_krw', 'stock_value_krw', 'total_assets_krw'
        ])


def reverse_migrate(apps, schema_editor):
    """역방향 마이그레이션: 통화별 필드를 기존 필드로 복사 (필드가 다시 생성된 경우)"""
    Account = apps.get_model('trading', 'Account')
    
    for account in Account.objects.all():
        # 통화별 필드를 기존 필드로 복사
        if hasattr(account, 'cash_balance'):
            account.cash_balance = account.cash_balance_krw
        if hasattr(account, 'stock_value'):
            account.stock_value = account.stock_value_krw
        if hasattr(account, 'total_assets'):
            account.total_assets = account.total_assets_krw
        
        account.save(update_fields=['cash_balance', 'stock_value', 'total_assets'])


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_account_cash_balance_krw_account_cash_balance_usd_and_more'),
    ]

    operations = [
        # 기존 데이터를 통화별 필드로 복사
        migrations.RunPython(migrate_legacy_fields_to_currency_fields, reverse_migrate),
        # 기존 필드 제거
        migrations.RemoveField(
            model_name='account',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_assets',
        ),
    ]
