# Generated by Django 4.2.27 on 2026-01-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_remove_legacy_asset_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='증권사 계좌번호 (암호화폐 거래소는 불필요)', max_length=100, null=True, verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_password',
            field=models.CharField(blank=True, help_text='증권사 계좌 비밀번호 (암호화폐 거래소는 불필요)', max_length=255, null=True, verbose_name='계좌비밀번호'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number__isnull', False)), fields=('user', 'broker', 'account_number'), name='unique_account_with_number'),
        ),
    ]
