# Generated by Django 4.2.27 on 2026-07-17 23:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trading.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_exchangefeerebate_exchange_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(verbose_name='원본 페이로드')),
                ('ticker', models.CharField(blank=True, default='', max_length=50, verbose_name='티커')),
                ('action', models.CharField(blank=True, choices=[('BUY', '매수'), ('SELL', '매도')], default='', max_length=10, verbose_name='액션')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='멱등 키')),
                ('status', models.CharField(choices=[('RECEIVED', '수신'), ('ACCEPTED', '수락'), ('REJECTED', '거부'), ('EXECUTING', '실행중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='RECEIVED', max_length=20, verbose_name='상태')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='거부 사유')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '알림 이벤트',
                'verbose_name_plural': '알림 이벤트들',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=10, verbose_name='매수/매도')),
                ('total_notional', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 금액')),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 수량 (매도)')),
                ('reference_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='기준가')),
                ('split_count', models.PositiveIntegerField(verbose_name='분할 횟수')),
                ('split_interval_seconds', models.PositiveIntegerField(default=0, verbose_name='분할 간격 (초)')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], default='MARKET', max_length=10, verbose_name='주문 타입')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SCHEDULED', '예약'), ('ORDERED', '주문생성'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('FAILED', '실패'), ('SKIPPED', '스킵')], default='PENDING', max_length=20, verbose_name='상태')),
                ('legs_done', models.PositiveIntegerField(default=0, verbose_name='완료된 Leg 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_trade_plans', to='trading.account', verbose_name='계좌')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plan', to='trading.alertevent', verbose_name='이벤트')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_trade_plans', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '알림 매매 계획',
                'verbose_name_plural': '알림 매매 계획들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTradeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='순번')),
                ('scheduled_at', models.DateTimeField(verbose_name='예약 시각')),
                ('notional', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액')),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SCHEDULED', '예약'), ('ORDERED', '주문생성'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('FAILED', '실패'), ('SKIPPED', '스킵')], default='SCHEDULED', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_trade_legs', to='trading.order', verbose_name='주문')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trading.alerttradeplan', verbose_name='계획')),
            ],
            options={
                'verbose_name': '알림 매매 Leg',
                'verbose_name_plural': '알림 매매 Legs',
                'ordering': ['plan', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='AlertStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='전략명')),
                ('webhook_token', models.CharField(default=trading.models.generate_webhook_token, help_text='URL path에 사용되는 고유 시크릿', max_length=64, unique=True, verbose_name='웹훅 토큰')),
                ('webhook_passphrase', models.CharField(blank=True, help_text='payload secret과 일치해야 함 (비우면 미검증)', max_length=128, null=True, verbose_name='웹훅 패스프레이즈')),
                ('seed_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='고정 시드 금액')),
                ('seed_currency', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], default='KRW', max_length=10, verbose_name='시드 통화')),
                ('buy_seed_percent', models.DecimalField(decimal_places=4, help_text='시드 금액 대비 매수 금액 비율', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='매수 시드 비율 (%)')),
                ('sell_seed_percent', models.DecimalField(decimal_places=4, help_text='시드 금액 대비 매도 금액 비율 (보유 수량으로 캡)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='매도 시드 비율 (%)')),
                ('max_position_weight_percent', models.DecimalField(decimal_places=4, default=Decimal('100'), help_text='시드 대비 종목 최대 보유 비중 (매수 상한)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='최대 포지션 비중 (%)')),
                ('min_sell_holding_percent', models.DecimalField(blank=True, decimal_places=4, help_text='보유 평가액이 시드 대비 이 비중 미만이면 매도 스킵 (선택)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='최소 매도 보유 비중 (%)')),
                ('split_count', models.PositiveIntegerField(default=1, help_text='1이면 일시 전량', validators=[django.core.validators.MinValueValidator(1)], verbose_name='분할 횟수')),
                ('split_interval_seconds', models.PositiveIntegerField(default=0, help_text='분할 횟수가 1보다 클 때 Leg 간 대기 시간', verbose_name='분할 간격 (초)')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], default='MARKET', max_length=10, verbose_name='주문 타입')),
                ('enabled', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('allowed_tickers', models.JSONField(blank=True, help_text='null/빈 목록이면 브로커 Symbol만 있으면 OK', null=True, verbose_name='허용 티커 목록')),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, help_text='동일 전략·티커·액션 중복 알림 완화', verbose_name='동일 티커 쿨다운 (초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_strategies', to='trading.account', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '알림 전략',
                'verbose_name_plural': '알림 전략들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading.alertstrategy', verbose_name='전략'),
        ),
        migrations.AddConstraint(
            model_name='alerttradeleg',
            constraint=models.UniqueConstraint(fields=('plan', 'seq'), name='unique_alert_trade_leg_seq'),
        ),
        migrations.AddConstraint(
            model_name='alertevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('strategy', 'idempotency_key'), name='unique_alert_event_idempotency'),
        ),
    ]
