# Generated by Django 4.2.27 on 2026-07-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_account_profit_by_currency'),
        ('trading', '0015_alert_strategy_models'),
    ]

    operations = [
    ]
