# Generated by Django 4.2.27 — edited for AlertStrategy → Strategy/StrategyLink data migration

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trading.models


def migrate_alert_strategies(apps, schema_editor):
    AlertStrategy = apps.get_model('trading', 'AlertStrategy')
    Strategy = apps.get_model('trading', 'Strategy')
    StrategyLink = apps.get_model('trading', 'StrategyLink')
    AlertTradePlan = apps.get_model('trading', 'AlertTradePlan')

    for old in AlertStrategy.objects.select_related('account').all():
        owner_id = old.account.user_id
        trade_pct = old.buy_seed_percent or old.sell_seed_percent or Decimal('10')
        strategy = Strategy(
            id=old.id,
            owner_id=owner_id,
            title=old.name,
            description='',
            visibility='PRIVATE',
            webhook_token=old.webhook_token,
            webhook_passphrase=old.webhook_passphrase,
            default_max_position_weight_percent=old.max_position_weight_percent,
            default_trade_percent=trade_pct,
            default_split_count=old.split_count or 1,
            default_split_interval_seconds=old.split_interval_seconds or 0,
            order_type=old.order_type or 'MARKET',
            enabled=old.enabled,
            allowed_tickers=old.allowed_tickers,
            cooldown_seconds=old.cooldown_seconds or 60,
            created_at=old.created_at,
            updated_at=old.updated_at,
        )
        strategy.save(force_insert=True)

        link = StrategyLink.objects.create(
            strategy_id=strategy.id,
            account_id=old.account_id,
            seed_amount=old.seed_amount,
            seed_currency=old.seed_currency or 'KRW',
            max_position_weight_percent=None,
            trade_percent=None,
            split_count=None,
            split_interval_seconds=None,
            enabled=old.enabled,
        )

        # Attach existing plans (same strategy id after FK retarget) to this link
        AlertTradePlan.objects.filter(
            account_id=old.account_id,
            event__strategy_id=old.id,
        ).update(strategy_link_id=link.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0016_merge_profit_and_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('visibility', models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비공개')], default='PRIVATE', max_length=10, verbose_name='공개 범위')),
                ('webhook_token', models.CharField(default=trading.models.generate_webhook_token, help_text='URL path에 사용되는 고유 시크릿', max_length=64, unique=True, verbose_name='웹훅 토큰')),
                ('webhook_passphrase', models.CharField(blank=True, help_text='payload secret과 일치해야 함 (비우면 미검증)', max_length=128, null=True, verbose_name='웹훅 패스프레이즈')),
                ('default_max_position_weight_percent', models.DecimalField(decimal_places=4, default=Decimal('100'), help_text='시드 대비 종목 최대 보유 비중 (매수 상한)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='default 최대 포지션 비중 (%)')),
                ('default_trade_percent', models.DecimalField(decimal_places=4, help_text='시드 금액 대비 매수/매도 금액 비율', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='default 매매당 비중 (%)')),
                ('default_split_count', models.PositiveIntegerField(default=1, help_text='1이면 일시 전량', validators=[django.core.validators.MinValueValidator(1)], verbose_name='default 분할 횟수')),
                ('default_split_interval_seconds', models.PositiveIntegerField(default=0, help_text='분할 횟수가 1보다 클 때 Leg 간 대기 시간', verbose_name='default 분할 기간 (초)')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], default='MARKET', max_length=10, verbose_name='주문 타입')),
                ('enabled', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('allowed_tickers', models.JSONField(blank=True, help_text='null/빈 목록이면 브로커 Symbol만 있으면 OK', null=True, verbose_name='허용 티커 목록')),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, help_text='동일 전략·티커·액션 중복 알림 완화', verbose_name='동일 티커 쿨다운 (초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '전략',
                'verbose_name_plural': '전략들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='고정 시드 금액')),
                ('seed_currency', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], default='KRW', max_length=10, verbose_name='시드 통화')),
                ('max_position_weight_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='최대 포지션 비중 override (%)')),
                ('trade_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='매매당 비중 override (%)')),
                ('split_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='분할 횟수 override')),
                ('split_interval_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='분할 기간 override (초)')),
                ('enabled', models.BooleanField(default=True, verbose_name='연동 활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_links', to='trading.account', verbose_name='계좌')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='trading.strategy', verbose_name='전략')),
            ],
            options={
                'verbose_name': '전략 연동',
                'verbose_name_plural': '전략 연동들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alerttradeplan',
            name='strategy_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_plans', to='trading.strategylink', verbose_name='전략 연동'),
        ),
        migrations.AlterField(
            model_name='alerttradeplan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plans', to='trading.alertevent', verbose_name='이벤트'),
        ),
        migrations.RunPython(migrate_alert_strategies, noop_reverse),
        migrations.AlterField(
            model_name='alertevent',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading.strategy', verbose_name='전략'),
        ),
        migrations.DeleteModel(
            name='AlertStrategy',
        ),
        migrations.AddConstraint(
            model_name='strategylink',
            constraint=models.UniqueConstraint(fields=('strategy', 'account'), name='unique_strategy_account_link'),
        ),
    ]
