# Generated by Django 4.2.27 on 2026-07-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_strategy_link_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SUBMITTING', '전송중'), ('PARTIALLY_FILLED', '부분체결'), ('FILLED', '체결완료'), ('CANCELLED', '취소됨'), ('REJECTED', '거부됨')], default='PENDING', max_length=20, verbose_name='주문상태'),
        ),
    ]
