# Generated by Django 4.2.27 on 2026-08-01 11:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0018_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('visibility', models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비공개')], default='PRIVATE', max_length=10, verbose_name='공개 범위')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], default='MARKET', max_length=10, verbose_name='주문 타입')),
                ('enabled', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='고정 시드 금액')),
                ('seed_currency', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], default='KRW', max_length=10, verbose_name='시드 통화')),
                ('enabled', models.BooleanField(default=True, verbose_name='연동 활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='trading.account', verbose_name='계좌')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='trading.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': '포트폴리오 연동',
                'verbose_name_plural': '포트폴리오 연동들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight_percent', models.DecimalField(decimal_places=2, help_text='포트폴리오 시드 대비 이 종목의 목표 비중', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='목표 비중 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.portfolio', verbose_name='포트폴리오')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '포트폴리오 종목',
                'verbose_name_plural': '포트폴리오 종목들',
                'ordering': ['-target_weight_percent'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='portfolio_link',
            field=models.ForeignKey(blank=True, help_text='포트폴리오 리밸런싱으로 생성된 주문인 경우 해당 연동', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.portfoliolink', verbose_name='포트폴리오 연동'),
        ),
        migrations.AddConstraint(
            model_name='portfoliolink',
            constraint=models.UniqueConstraint(fields=('portfolio', 'account'), name='unique_portfolio_account_link'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'symbol'), name='unique_portfolio_symbol'),
        ),
    ]
