# Generated by Django 4.2.27 on 2026-08-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_portfolio_portfoliolink_portfolioholding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='ticker',
            field=models.CharField(max_length=50, verbose_name='티커'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('broker', 'ticker'), name='unique_broker_ticker'),
        ),
    ]
