# Generated by Django 4.2.27 on 2026-08-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_alter_symbol_ticker_symbol_unique_broker_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('chamber', models.CharField(choices=[('SENATE', '상원'), ('HOUSE', '하원')], max_length=10, verbose_name='상/하원')),
                ('party', models.CharField(blank=True, default='', max_length=50, verbose_name='정당')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='주')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('portfolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congress_member', to='trading.portfolio', verbose_name='연동 포트폴리오')),
            ],
            options={
                'verbose_name': '의회의원',
                'verbose_name_plural': '의회의원들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CongressTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ticker', models.CharField(blank=True, default='', help_text='Symbol 매칭 실패 시(채권/옵션/비상장 등) 원본 텍스트 보관', max_length=50, verbose_name='원본 티커')),
                ('asset_description', models.CharField(blank=True, default='', max_length=300, verbose_name='자산 설명')),
                ('transaction_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('EXCHANGE', '교환')], max_length=10, verbose_name='거래유형')),
                ('transaction_date', models.DateField(verbose_name='거래일')),
                ('disclosure_date', models.DateField(blank=True, null=True, verbose_name='공시일')),
                ('amount_min', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='거래금액 최소')),
                ('amount_max', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='거래금액 최대')),
                ('source_url', models.CharField(blank=True, default='', max_length=500, verbose_name='출처 URL')),
                ('crawled_at', models.DateTimeField(verbose_name='크롤링 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.congressmember', verbose_name='의원')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congress_trades', to='trading.symbol', verbose_name='매칭된 종목')),
            ],
            options={
                'verbose_name': '의회 공시 거래',
                'verbose_name_plural': '의회 공시 거래들',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='congresstrade',
            constraint=models.UniqueConstraint(fields=('member', 'raw_ticker', 'transaction_type', 'transaction_date', 'amount_min', 'amount_max'), name='unique_congress_trade'),
        ),
        migrations.AddConstraint(
            model_name='congressmember',
            constraint=models.UniqueConstraint(fields=('name', 'chamber'), name='unique_congress_member'),
        ),
    ]
