# Generated by Django 4.2.27 on 2026-08-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_alter_symbol_ticker_symbol_unique_broker_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolink',
            name='seed_currency',
            field=models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('JPY', '엔'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], default='KRW', max_length=10, verbose_name='시드 통화'),
        ),
        migrations.AlterField(
            model_name='strategylink',
            name='seed_currency',
            field=models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('JPY', '엔'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], default='KRW', max_length=10, verbose_name='시드 통화'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='currency',
            field=models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('JPY', '엔'), ('USDT', '테더'), ('BTC', '비트코인'), ('ETH', '이더리움')], max_length=10, verbose_name='화폐단위'),
        ),
    ]
