# Generated by Django 4.2.27 on 2026-08-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_congressmember_congresstrade_and_more'),
        ('trading', '0022_alter_portfoliolink_seed_currency_and_more'),
    ]

    operations = [
    ]
