# Generated by Django 4.2.27 on 2026-08-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_merge_20260809_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='dart_corp_code',
            field=models.CharField(blank=True, help_text='국내(KR) 종목의 DART corp_code 캐시. corpCode.xml 매핑 결과(ARCH-0002)', max_length=8, null=True, verbose_name='DART 고유번호'),
        ),
        migrations.CreateModel(
            name='KrFinancialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsns_year', models.CharField(max_length=4, verbose_name='사업연도')),
                ('reprt_code', models.CharField(choices=[('11013', '1분기보고서'), ('11012', '반기보고서'), ('11014', '3분기보고서'), ('11011', '사업보고서')], max_length=5, verbose_name='보고서 구분')),
                ('fs_div', models.CharField(default='CFS', help_text='CFS=연결재무제표, OFS=별도재무제표(연결 미제출 시 fallback)', max_length=3, verbose_name='재무제표 구분')),
                ('revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='매출액')),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='영업이익')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='당기순이익')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_financial_facts', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '국내 종목 분기 실적',
                'verbose_name_plural': '국내 종목 분기 실적들',
                'ordering': ['-bsns_year', '-reprt_code'],
            },
        ),
        migrations.CreateModel(
            name='KrDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=8, verbose_name='DART 고유번호')),
                ('corp_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('rcept_no', models.CharField(max_length=20, unique=True, verbose_name='접수번호')),
                ('report_name', models.CharField(max_length=300, verbose_name='보고서명')),
                ('rcept_dt', models.DateField(help_text='DART 공시검색 API는 접수 "시각"을 제공하지 않아 일자만 저장한다 (ADR-0003)', verbose_name='접수일자')),
                ('source_url', models.URLField(max_length=500, verbose_name='원문 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_disclosures', to='trading.symbol', verbose_name='종목')),
            ],
            options={
                'verbose_name': '국내 종목 공시',
                'verbose_name_plural': '국내 종목 공시들',
                'ordering': ['-rcept_dt', '-rcept_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='krfinancialfact',
            constraint=models.UniqueConstraint(fields=('symbol', 'bsns_year', 'reprt_code'), name='unique_kr_financial_fact'),
        ),
        migrations.AddIndex(
            model_name='krdisclosure',
            index=models.Index(fields=['symbol', '-rcept_dt'], name='trading_krd_symbol__f5438b_idx'),
        ),
    ]
